# Generated by Django 5.2.1 on 2025-06-10 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={},
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='created_at',
            new_name='uploaded_at',
        ),
        migrations.RenameField(
            model_name='photodislike',
            old_name='created_at',
            new_name='uploaded_at',
        ),
        migrations.RenameField(
            model_name='photolike',
            old_name='created_at',
            new_name='uploaded_at',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='created_at',
            new_name='uploaded_at',
        ),
        migrations.AlterUniqueTogether(
            name='photodislike',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='photolike',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='photo',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='uploaded_by',
        ),
        migrations.AlterField(
            model_name='photodislike',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.photo'),
        ),
        migrations.AlterField(
            model_name='photodislike',
            name='user',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='photolike',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.photo'),
        ),
        migrations.AlterField(
            model_name='photolike',
            name='user',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='photodislike',
            unique_together={('photo', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='photolike',
            unique_together={('photo', 'user')},
        ),
    ]
